### ISSUE TITLE
Notational conflict: \sigma

### ISSUE THREAD

**Issue by ketch** [ketch/shallow_water_periodic_bathymetry#4]
We use \sigma as part of our standard initial condition and also as the coefficient of surface tension.

**Comment by manuel-quezada** [comment]
PR #5 fixes this issue. I made the macro \ST for \sigma^{\scriptsize \text{ST}} which I am using to denote the coefficient for the surface tension.

**Comment by ketch** [comment]
I avoid using multiple consecutive letters to denote a single quantity, since this is too easily confused with a product.  Perhaps just pick another greek letter?

**Comment by manuel-quezada** [comment]
Fair enough. I changed it to \gamma which apparently is also commonly used. For example, \gamma is the symbol used in Wikipedia (https://en.wikipedia.org/wiki/Surface_tension).
