### ISSUE TITLE
General issues 

### ISSUE THREAD

**Issue by manuel-quezada** [ketch/shallow_water_periodic_bathymetry#7]
I will put here all things I find that require attention or fixing. I will be updating the to-do list. 

- [x] In figure 4, the initial condition is not correct. It must be \eta_0=0.75 and \epsilon=0.05 with the corresponding variances. 
- [x] Update the results in section 3 using g=9.8 instead of 1.

**Comment by ketch** [comment]
[ ] The pcolor plots in Figure 4 should be restricted to just the channel domain (-1/4,1/4).

**Comment by manuel-quezada** [comment]
I will handle this issue with PR #9

**Comment by manuel-quezada** [comment]
I am working on PR #10  to deal with the reproducibility.
